project/src/java/addhandler/ProductMB.java
package addhandler;

import dao.AddDao;
import dao.ListDao;
import entity.Product;
import entity.SubCategory;
import java.io.File;
import java.io.InputStream;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.servlet.ServletContext;
import org.apache.commons.io.FileUtils;
import org.primefaces.model.UploadedFile;


@ManagedBean(name = "obj3") 
@SessionScoped 

public class ProductMB 
{ 
    Product product = new Product();
    SubCategory subcat = new SubCategory();
    
    String subcatname;
    String catname = "";
    List<SubCategory> listsubcat;
    
    UploadedFile file;
    
    
    // Getter & Setter

    public Product getProduct() {
        return product;
    } 

    public void setProduct(Product product) { 
        this.product = product;
    }

    public SubCategory getSubcat() {
        return subcat;
    }

    public void setSubcat(SubCategory subcat) {
        this.subcat = subcat;
    }

    public String getSubcatname() {
        return subcatname;
    }

    public void setSubcatname(String subcatname) {
        this.subcatname = subcatname;
    }

    public String getCatname() {
        return catname;
    }

    public void setCatname(String catname) {
        this.catname = catname;
    }

    public List<SubCategory> getListsubcat() {
        return listsubcat;
    }

    public void setListsubcat(List<SubCategory> listsubcat) {
        this.listsubcat = listsubcat;
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    
    
    
    
    public String addProduct() 
    { 
        upload();
        
        listsubcat = new ListDao().subcatListByName(subcatname); 
        
        subcat.setSubCatId(listsubcat.get(0).getSubCatId()); 
        product.setSubCategory(subcat);
        
        product.setProName(product.getProName());
        product.setProQty(product.getProQty());
        product.setProPrice(product.getProPrice());
        product.setProImgUrl(product.getProImgUrl());
        product.setProDesc(product.getProDesc());
        
        boolean status = new AddDao().addProduct(product);
        if(status) 
        { 
            FacesContext.getCurrentInstance().addMessage(null, new 
            FacesMessage(FacesMessage.SEVERITY_INFO, "Data Saved Successfully", ""));
        } 
        else
        { 
            FacesContext.getCurrentInstance().addMessage(null, new 
                         FacesMessage(FacesMessage.SEVERITY_WARN, "Data not Saved", ""));
        } 
        return null;
    } 
    
    
    
    
    
    public void upload() 
    { 
        if(file != null) 
        { 
            try 
            { 
                FacesContext context = FacesContext.getCurrentInstance();
                ServletContext servletcontext = (ServletContext) context.getExternalContext().getContext();
                
                String dbpath = servletcontext.getRealPath("/"); // taking root path
                String webcut = dbpath.substring(0, dbpath.lastIndexOf("\\")); 
                String buildcut = webcut.substring(0, webcut.lastIndexOf("\\")); 
                String mainURLpath = buildcut.substring(0, buildcut.lastIndexOf("\\")); 

                InputStream inputstream = file.getInputstream(); 
                String path = mainURLpath + "\\web\\resources\\images\\" + file.getFileName(); 
                
                File destFile = new File(path); 
                
                if(!destFile.exists()) 
                { 
                    FileUtils.copyInputStreamToFile(inputstream, destFile);
                } 
                
                product.setProImgUrl(file.getFileName().toString());
            } 
            catch (Exception e) 
            { 
                e.printStackTrace();
            } 
        } 
        
    } 
    
    public List<SelectItem> getSubCategoryName() 
    {
        List<SelectItem> subcatname = new ListDao().subcatList(catname);
        return subcatname;
    }
} 

project/src/java/addhandler/SubCategoryMB.java
package addhandler;

import dao.AddDao;
import dao.ListDao;
import entity.Category;
import entity.SubCategory;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

@ManagedBean(name = "obj2") 
@SessionScoped
public class SubCategoryMB 
{
    SubCategory subcat = new SubCategory();
    Category category = new Category();
    String catname;
    List<Category> listcat;

    
    // Setter & Getter
    public List<Category> getListcat() {
        return listcat;
    }

    public void setListcat(List<Category> listcat) {
        this.listcat = listcat;
    }

    public SubCategory getSubcat() {
        return subcat;
    }

    public void setSubcat(SubCategory subcat) {
        this.subcat = subcat;
    }

    public String getCatname() {
        return catname;
    }

    public void setCatname(String catname) {
        this.catname = catname;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }
    
    // Setter & Getter close
    
    
    
    
    
    
    
    public String addSubCategory()
    {
        listcat = new ListDao().catListByName(catname);
        
        category.setCatId(listcat.get(0).getCatId());
        
        subcat.setCategory(category);
        subcat.setSubCatName(subcat.getSubCatName());
        subcat.setSubCatDesc(subcat.getSubCatDesc());
        
        boolean status = new AddDao().addSubCategory(subcat);
        if(status)
        { 
            FacesContext.getCurrentInstance().addMessage(null, new 
            FacesMessage(FacesMessage.SEVERITY_INFO, "Data Saved Successfully", ""));
        } 
        else
        { 
            FacesContext.getCurrentInstance().addMessage(null, new 
                         FacesMessage(FacesMessage.SEVERITY_WARN, "Data not Saved", ""));
        } 
        return null;
    }
    
    
    public List<SelectItem> getCategoryName()
    {
        List<SelectItem> catname = new ListDao().catList();
        
        return catname;
    }
}

project/web/admin/addcategory.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head> 
        
        <title>ProgGyan ONLINE</title> 
        
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <script src="resources/js/jquery-3.3.1.min.js"></script> 
        <script href="resources/js/bootstrap.min.js"></script> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        
    </h:head> 
    
    
    
    
    <h:body> 
        
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 
            </div> 
        </div> 
        
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 

        
        
        <div class="container contentsection"> 
            <div class="leftbar col-lg-3"> 
                <h3 class="header"><h:outputLabel value="ProgGyan ONLINE"/></h3>
                <f:view> 
                    <h:form> 
                        <h4><h:commandLink class="adminlink" value="Add Catagory" action="/admin/addcategory.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Sub-Catagory" action="/admin/addsubcat.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Product" action="/admin/addproduct.xhtml"/></h4> 
                    </h:form> 
                </f:view> 
            </div> 
            
            <div class="rightbar col-lg-9"> 
                <h2>Admin Panel</h2> 
                <hr/> 
                
                <div class="col-lg-offset-1">
                    <f:view> 
                        <h:form>  
                            <p:messages id="msg" closable="true" showDetail="true"/>
                            <p:panelGrid columns="2"> 
                                <h:outputLabel value="Category Name"/> 
                                <p:inputText value="#{obj.category.catName}"/> 

                                <h:outputLabel value="Category Description"/> 
                                <p:inputTextarea value="#{obj.category.catDesc}"/> 
                            </p:panelGrid> 
                            
                            <p:commandButton class="btn btn-primary" update="msg" value="Save" action="#{obj.addCategory()}"/> 
                        </h:form> 
                    </f:view> 
                </div> 
            </div> 
                
        </div> 
        
        
        
        
        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                            <i class="fa fa-facebook"></i> </a> </li> 
                             
                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 
        
        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div>
        
    </h:body>
</html>

project/web/admin/addproduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 
    
    
    
    
    <h:head> 
        
        <title>ProgGyan ONLINE</title> 
        
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        
    </h:head> 
    
    <h:body> 
        
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 
            </div> 
        </div> 
        
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 

        
        
        <div class="container contentsection"> 
            <div class="leftbar2 col-lg-3"> 
                <h3 class="header"><h:outputLabel value="ProgGyan ONLINE"/></h3>
                <f:view> 
                    <h:form> 
                        <h4><h:commandLink class="adminlink" value="Add Catagory" action="/admin/addcategory.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Sub-Catagory" action="/admin/addsubcat.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Product" action="/admin/addproduct.xhtml"/></h4> 
                    </h:form> 
                </f:view> 
            </div> 
            
            <div class="rightbar2 col-lg-9"> 
                <h2>Admin Panel</h2> 
                <hr/> 
                
                <div class="col-lg-offset-1">
                    <f:view> 
                        <h:form enctype="multipart/form-data"> 

                            <p:messages id="msg" closable="true" showDetail="true"/> 
                            <p:panelGrid columns="2"> 

                                <h:outputLabel value="Select Category Name"/> 
                                <p:selectOneMenu value="#{obj3.catname}"> 
                                    <f:selectItem itemLabel="Select Category Name" itemValue="" /> 
                                    <f:selectItems value="#{obj2.categoryName}" /> 
                                    <p:ajax update="scat"/>
                                </p:selectOneMenu> 


                                <h:outputLabel value="Select Sub-Category Name"/> 
                                <p:selectOneMenu value="#{obj3.subcatname}" id="scat"> 
                                    <f:selectItem itemLabel="Select Sub-Category Name" itemValue="" /> 
                                    <f:selectItems value="#{obj3.subCategoryName}"/> 
                                </p:selectOneMenu> 




                                <h:outputLabel value="Product Name"/> 
                                <p:inputText value="#{obj3.product.proName}"/> 

                                <h:outputLabel value="Product Quantity"/> 
                                <p:inputText value="#{obj3.product.proQty}"/> 

                                <h:outputLabel value="Product Price"/> 
                                <p:inputText value="#{obj3.product.proPrice}"/> 

                                <h:outputLabel value="Select Image"/> 
                                <p:fileUpload value="#{obj3.file}" mode="simple"/> 

                                <h:outputLabel value="Product Description"/> 
                                <p:inputTextarea value="#{obj3.product.proDesc}"/>
                            </p:panelGrid> 
                            
                            
                            <p:commandButton class="btn btn-primary" action="#{obj3.addProduct()}" value="Save" update="msg" ajax="false"/> 
                        </h:form> 
                    </f:view> 
                </div> 
            </div> 
        </div> 
        
        
        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                            <i class="fa fa-facebook"></i> </a> </li> 
                             
                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 
        
        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div>
        
    </h:body> 
</html> 

project/web/admin/addsubcat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 
    
    
    
    
    <h:head> 
        
        <title>ProgGyan ONLINE</title> 
        
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        
    </h:head> 
    
    <h:body> 
        
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 
            </div> 
        </div> 
        
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 

        
        
        <div class="container contentsection"> 
            <div class="leftbar col-lg-3"> 
                <h3 class="header"><h:outputLabel value="ProgGyan ONLINE"/></h3>
                <f:view> 
                    <h:form> 
                        <h4><h:commandLink class="adminlink" value="Add Catagory" action="/admin/addcategory.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Sub-Catagory" action="/admin/addsubcat.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Product" action="/admin/addproduct.xhtml"/></h4> 
                    </h:form> 
                </f:view> 
            </div> 
            
            <div class="rightbar col-lg-9"> 
                <h2>Admin Panel</h2> 
                <hr/> 
                
                <div class="col-lg-offset-1">
                    <f:view> 
                        <h:form> 
                            <p:messages id="msg" closable="true" showDetail="true"/> 
                            <p:panelGrid columns="2"> 
                                <h:outputLabel value="Select Category Name"/> 
                                <p:selectOneMenu value="#{obj2.catname}"> 
                                    <f:selectItem itemLabel="Select Category Name" itemValue="" /> 
                                    <f:selectItems value="#{obj2.categoryName}" /> 
                                </p:selectOneMenu> 

                                <h:outputLabel value="Sub Category Name"/> 
                                <p:inputText value="#{obj2.subcat.subCatName}"/> 

                                <h:outputLabel value="Sub Category Description"/> 
                                <p:inputTextarea value="#{obj2.subcat.subCatDesc}"/> 
                            </p:panelGrid> 
                            
                            <p:commandButton class="btn btn-primary" update="msg" value="Save" action="#{obj2.addSubCategory()}"/> 
                        </h:form> 
                    </f:view> 
                </div> 
            </div> 
        </div> 
        
        
        
        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                            <i class="fa fa-facebook"></i> </a> </li> 
                             
                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 
        
        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div>
        
    </h:body> 
</html> 