project/src/java/display/DisplayProductMB.java
package display;

import dao.ListDao;
import entity.Product;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "obj4")
@SessionScoped
public class DisplayProductMB 
{ 
    Product product = new Product(); 
    private Product selectedProduct;
    
    
    
    public Product getSelectedProduct() {
        return selectedProduct;
    }

    public void setSelectedProduct(Product selectedProduct) {
        this.selectedProduct = selectedProduct;
    }
    
    public Product getProduct() { 
        return product;
    } 

    public void setProduct(Product product) { 
        this.product = product;
    } 
    
    public List<Product> getAllProduct() 
    { 
        List<Product> plist = new ListDao().allProductList();
        return plist;
    } 
} 

project/web/aboutus.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head> 
        
        <title>OS Project</title> 
        
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <script src="resources/js/jquery-3.3.1.min.js"></script> 
        <script href="resources/js/bootstrap.min.js"></script> 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        
        
        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        <link rel="stylesheet" href="resources/css/font-awesome.min.css"></link> 
        
    </h:head> 
    
    
    
    <h:body> 
       
        
        <!--Logo--> 
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 
            </div> 
        </div> 


        <!--Navbar--> 
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 


        
        
        
        
        <section> 
            
            <h1 class="info col-lg-offset-5">Our Information</h1> 
            
            <div class="container-fluid"> 
                <div class="container"> 
                    <div class="member row"> 
                        <div class="col-sm-3"> 
                            <div class="imageBox"> 
                                <img class="img-responsive img-circle img-thumbnail" src="Image/me.jpg"/>
                                <h3> Md Rijyan Hossain </h3> 
                                <b class="col-lg-offset-3">ID = 152002007</b> 
                                <ul>
                                    <li> <a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                                         <i class="fa fa-facebook"></i> </a> </li> 
                                         
                                    
                                    <li> <a href="#"> 
                                         <i class="fa fa-google"></i> 
                                         </a> </li> 
                                </ul>
                            </div> 
                        </div> 
                        
                        <div class="col-sm-3"> 
                            <div class="imageBox"> 
                                <img class="img-responsive img-circle img-thumbnail" src="Image/nafis.png"/>
                                <h3 class="skcolor"> Sk Nafis Istiak </h3> 
                                <b class="col-lg-offset-3">ID = 152002024</b> 
                                <ul>
                                    <li> <a href="https://www.facebook.com/profile.php?id=100008431961442"> 
                                         <i class="fa fa-facebook"></i> </a> </li> 
                                         
                                    <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                                </ul>
                            </div> 
                        </div> 
                        
                        <div class="col-sm-3"> 
                            <div class="imageBox"> 
                                <img class="img-responsive img-circle img-thumbnail" src="Image/nafis.png"/>
                                <h3 class="skcolor"> Mst. Shithi Khatun </h3> 
                                <b class="col-lg-offset-3">ID = 151002033</b> 
                                <ul>
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li> 
                                         
                                    <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                                </ul> 
                            </div> 
                        </div> 
                        
                        <div class="col-sm-3"> 
                            <div class="imageBox"> 
                                <img class="img-responsive img-circle img-thumbnail" src="Image/nafis.png"/>
                                <h3 class="skcolor"> Mst. Sanjida Khatun </h3> 
                                <b class="col-lg-offset-3">ID = 151002036</b> 
                                <ul>
                                    <li> <a href="https://www.facebook.com/profile.php?id=100012712157988"> 
                                         <i class="fa fa-facebook"></i> </a> </li> 
                                         
                                    <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                                </ul>
                            </div> 
                        </div> 
                    </div> 
                </div> 
            </div> 
        </section> 
        
        
        
        
        <br/><br/><br/>
        
        
        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                            <i class="fa fa-facebook"></i> </a> </li> 
                             
                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 
        
        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div> 
        
        
        
        
    </h:body> 
</html> 

project/web/adminpanel.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head> 
        
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <script src="resources/js/jquery-3.3.1.min.js"></script> 
        <script href="resources/js/bootstrap.min.js"></script> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>

        <title>ProgGyan ONLINE</title>

        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        
    </h:head> 
    
    
    
    
    <h:body> 
        
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 
            </div> 
        </div> 
        
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 

        
        
        <div class="container contentsection"> 
            <div class="leftbar col-lg-3"> 
                <h3 class="header"><h:outputLabel value="ProgGyan ONLINE"/></h3>
                <f:view> 
                    <h:form> 
                        <h4><h:commandLink class="adminlink" value="Add Catagory" action="/admin/addcategory.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Sub-Catagory" action="/admin/addsubcat.xhtml"/></h4> 
                        <h4><h:commandLink class="adminlink" value="Add Product" action="/admin/addproduct.xhtml"/></h4> 
                    </h:form> 
                </f:view> 
            </div> 
            
            <div class="rightbar col-lg-9"> 
                <h2>Admin Panel</h2> 
                <hr/>
            </div> 
                
        </div> 
        
        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                            <i class="fa fa-facebook"></i> </a> </li> 
                             
                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 
        
        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div>
        
    </h:body>
</html>

project/web/display.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"> 
    
    
    <h:head> 
        <title>ProgGyan ONLINE</title>

        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
    </h:head> 
    
    
    
    
    <h:body> 
        
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 

            </div> 
        </div> 
        
        
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 

        
        
        
        <div class="container" style="background-color: #0083B9"> 
        
            <f:view> 
                <h:form id="form"> 

                    <p:panel header="Cart"> 
                        <h:outputText value="#{obj5.cartsize} #{obj5.item}" id="cart"/> <br/> <br/> 
                        <h:commandButton class="btn btn-primary" value="Show My Cart" action="viewcart.xhtml"/> 
                    </p:panel> 




                    <p:dataGrid var="product" value="#{obj4.allProduct}" columns="3" rows="9" paginator="true" id="p" 
                                paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}" rowsPerPageTemplate="6,12,16">

                        <f:facet name="header"> 
                            <h:outputLabel value="All Products"/> 
                        </f:facet> 


                        <p:panel header="#{product.proName}">
                            <h:panelGrid columns="1">
                                <h:graphicImage name="#{product.proImgUrl}" library="images" width="180" height="200"/>
                                <h:outputText  value="#{product.proPrice} TK/-"/> 

                                <h:outputLabel value="Quantity"/> 
                                <h:inputText binding="#{input1}"/>

                                <p:commandButton class="btn btn-info" action="#{obj5.processCart(input1.value)}" value="Add to Cart" update=":form:cart">
                                    <f:setPropertyActionListener target="#{obj5.productid}" value="#{product.proId}"/>
                                    <f:setPropertyActionListener target="#{obj5.productname}" value="#{product.proName}"/>
                                    <f:setPropertyActionListener target="#{obj5.price}" value="#{product.proPrice}"/>
                                </p:commandButton> 
                            </h:panelGrid> 



                            <p:commandLink update=":form:pro" oncomplete="PF('proDetails').show()" title="View Details">
                                <!-- <h:outputText styleClass="ui-icon ui-icon-search"/> --> 
                                <h:outputText class="btn btn-info" value="Details"/> 
                                <f:setPropertyActionListener value="#{product}" target="#{obj4.selectedProduct}"/>
                            </p:commandLink> 
                        </p:panel> 
                    </p:dataGrid> 






                    <p:dialog header="Product Info" widgetVar="proDetails" modal="true" 
                              showEffect="fade" hideEffect="fade" rendererType="false"> 

                        <p:outputPanel id="pro"> 
                            <p:panelGrid columns="2" styleClass="ui-responsive"> 
                                <f:facet name="header"> 
                                    <h:graphicImage name="#{obj4.selectedProduct.proImgUrl}" library="images" width="180" height="215"/> 
                                </f:facet> 

                                <h:outputText value="Product Name"/> 
                                <h:outputText value="#{obj4.selectedProduct.proName}"/> 

                                <h:outputText value="Product Price"/> 
                                <h:outputText value="#{obj4.selectedProduct.proPrice} BDT"/> 

                                <h:outputText value="Description"/> 
                                <h:outputText value="#{obj4.selectedProduct.proDesc}"/> 
                            </p:panelGrid> 
                        </p:outputPanel> 
                    </p:dialog> 
                </h:form> 
            </f:view> 
        </div> 
    </h:body> 
</html> 

project/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core"> 
    <h:head> 

        <title>OS Project</title> 

        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 
        <link rel="stylesheet" href="resources/css/font-awesome.min.css"></link> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
    </h:head>  




    <h:body> 

        <!--Logo--> 
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 

            </div> 
        </div> 



        <!--Navbar--> 
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 






        <!--Image Slider--> 
        <div class="container"> 
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators --> 
                <ol class="carousel-indicators"> 
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol> 

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="carousel-inner"> 
                        <div class="item active"> 
                            <img class="img-responsive" src="Image/a.jpg" alt="Los Angeles" styleClass="width:100%;"/>
                        </div> 

                        <div class="item"> 
                            <img class="img-responsive" src="Image/c.jpg" alt="Chicago" styleClass="width:100%;"/>
                        </div> 

                        <div class="item"> 
                            <img class="img-responsive" src="Image/b.jpg" alt="New York" styleClass="width:100%;"/>
                        </div> 
                    </div>  
                </div> 



                <!-- Left and right controls --> 
                <a class="left carousel-control" href="#myCarousel" data-slide="prev"> 
                    <span class="glyphicon glyphicon-chevron-left"></span> 
                    <span class="sr-only">Previous</span> 
                </a> 
                <a class="right carousel-control" href="#myCarousel" data-slide="next"> 
                    <span class="glyphicon glyphicon-chevron-right"></span> 
                    <span class="sr-only">Next</span> 
                </a> 
            </div> 
        </div> 




        <div class="container"> 

            <f:view> 
                <h:form id="form"> 

                    <p:dataGrid var="product" value="#{obj4.allProduct}" columns="3" rows="9" paginator="true" id="p" 
                                paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}" rowsPerPageTemplate="6,12,16">

                        <f:facet name="header"> 
                            <h3><h:outputLabel value="All Products"/></h3>  
                        </f:facet> 


                        <p:panel header="#{product.proName}">
                            <h:panelGrid columns="1">
                                <h:graphicImage name="#{product.proImgUrl}" library="images" width="180" height="200"/>
                                <h:outputText  value="#{product.proPrice} TK/-"/> 

                                <h:outputLabel value="Quantity"/> 
                                <h:inputText binding="#{input1}"/>

                                <p:commandButton class="btn btn-info" style="color: black;" action="#{obj5.processCart(input1.value)}" value="Add to Cart" update=":form:cart">
                                    <f:setPropertyActionListener target="#{obj5.productid}" value="#{product.proId}"/>
                                    <f:setPropertyActionListener target="#{obj5.productname}" value="#{product.proName}"/>
                                    <f:setPropertyActionListener target="#{obj5.price}" value="#{product.proPrice}"/>
                                </p:commandButton> 
                            </h:panelGrid> 



                            <p:commandLink update=":form:pro" oncomplete="PF('proDetails').show()" title="View Details">
                                <!-- <h:outputText styleClass="ui-icon ui-icon-search"/> --> 
                                <h:outputText class="btn btn-info" value="Details"/> 
                                <f:setPropertyActionListener value="#{product}" target="#{obj4.selectedProduct}"/>
                            </p:commandLink> 
                        </p:panel> 
                    </p:dataGrid> 



                    <p:panel header="Cart"> 
                        <h:outputText value="#{obj5.cartsize} #{obj5.item}" id="cart"/> <br/> <br/> 
                        <h:commandButton class="btn btn-primary" value="Show My Cart" action="viewcart.xhtml"/> 
                    </p:panel> 



                    <p:dialog header="Product Info" widgetVar="proDetails" modal="true" 
                              showEffect="fade" hideEffect="fade" rendererType="false"> 

                        <p:outputPanel id="pro"> 
                            <p:panelGrid columns="2" styleClass="ui-responsive"> 
                                <f:facet name="header"> 
                                    <h:graphicImage name="#{obj4.selectedProduct.proImgUrl}" library="images" width="180" height="215"/> 
                                </f:facet> 

                                <h:outputText value="Product Name"/> 
                                <h:outputText value="#{obj4.selectedProduct.proName}"/> 

                                <h:outputText value="Product Price"/> 
                                <h:outputText value="#{obj4.selectedProduct.proPrice} BDT"/> 

                                <h:outputText value="Description"/> 
                                <h:outputText value="#{obj4.selectedProduct.proDesc}"/> 
                            </p:panelGrid> 
                        </p:outputPanel> 
                    </p:dialog> 
                </h:form> 
            </f:view> 
        </div> 

        <!-- Show Product Finish -->






        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                                <i class="fa fa-facebook"></i> </a> </li> 

                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 

        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div>


        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </h:body> 
</html> 

project/web/mission.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"> 
    <h:head> 
        
        <title>ProgGyan ONLINE</title> 
        
        <link rel="stylesheet" href="resources/css/bootstrap.min.css"></link> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link rel="stylesheet" href="resources/css/CustomCSS.css"></link> 

    </h:head> 




    <h:body> 

        <!--Logo--> 
        <div class="container"> 
            <div class="row"> 
                <div class="col-lg-6 col-md-6 col-xs-6"> 
                    <img class="img img-responsive" src="Image/logo.png"/> 
                </div> 
            </div> 
        </div> 



        <!--Navbar--> 
        <nav class="navbar"> 
            <div class="navsection container-fluid"> 
                <div class="container"> 
                    <ul class="nav navbar-nav"> 
                        <li class="active"><a class="navtext" href="index.xhtml">Home</a></li> 
                        <li class="navli"><a class="navtext" href="aboutus.xhtml">About Us</a></li> 
                        <li class="navli"><a class="navtext" href="mission.xhtml">Our Mission</a></li> 
                        <li class="navli"><a class="navtext" href="display.xhtml">Product</a></li> 
                        <li class="navli"><a class="navtext" href="adminpanel.xhtml">Admin Panel</a></li> 
                    </ul> 
                </div> 
            </div> 
        </nav> 


        <div class="container jumbotron" style="margin-bottom: -2px;"> 
            <h2>Our Mission</h2>  
            <ol> 
                <li><b>We want A+</b></li> 
                <li> 
                    That's our very first course where we are really trying to make a complete web site. <br/> 
                    By making this site, our mission is exploring our knowledge and developing skill to be a professional developer.
                    
                </li> 
            </ol> 
        </div> 


        
        <div class="container sndfotr"> 
            <div class="row jumbotron" style="background: #010114;"> 
                <div class="leftjumb col-lg-offset-2 col-lg-6"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Address"/></h3> 
                    <address style="color: whitesmoke;"> 
                        #Road-10, #House-2, #Block-H, Mirpur-2 <br/> Dhaka-Bangladesh <br/> 
                        <b>Cell:</b> 01996813160, 01674035897 <br/> 
                        <p style="font-size: 15px; color: #368132;"><b style="color: white;">Email:</b> rijyan.cse.152@gmail.com</p> <br/> 
                    </address> 
                </div> 

                <div class="rightjumb"> 
                    <h3 style="color: whitesmoke;"><h:outputLabel value="Quick Contact"/></h3> 
                    <ul> 
                        <li><a href="https://www.facebook.com/profile.php?id=100009568695942"> 
                            <i class="fa fa-facebook"></i> </a> </li> 
                             
                        <li> <a href="#"> <i class="fa fa-google"></i> </a> </li> 
                    </ul> 
                </div> 
            </div> 
        </div> 
        
        <div class="container footer well-sm" style="padding-top: 25px; text-align: center; top: 20px; background: #0B0B21;">
            <p style="color: white;">Copyright &copy; 2018 <b style="color: #368132;">Dark Army</b> || All rights reserved.</p>
        </div> 
    </h:body> 
</html> 